### ISSUE TITLE
Version 0.11.1 failing with java.io.FileNotFoundException: need to disable scoverage during build/packaging

### ISSUE THREAD

**Issue by barryperez-sky** [Tinkoff/gatling-kafka-plugin#152]
Hi,

Thanks for looking into the issue I raised regarding EL not working (#147). I just updated to use the latest plugin version 0.11.1 but the test fails at runtime with the following:

```
09:03:24.720 [ERROR] i.g.a.Gatling$ - Run crashed
java.io.FileNotFoundException: /home/runner/work/gatling-kafka-plugin/gatling-kafka-plugin/target/scala-2.13/scoverage-data/scoverage.measurements.6cf3fc58-0f63-4d63-8e4c-caa4ebb803be.1 (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileWriter.<init>(FileWriter.java:113)
	at scoverage.Invoker$.$anonfun$invoked$1(Invoker.scala:65)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:454)
	at scoverage.Invoker$.invoked(Invoker.scala:65)
	at ru.tinkoff.gatling.kafka.protocol.KafkaProtocolBuilderPropertiesStep.properties(KafkaProtocolBuilderPropertiesStep.scala:6)
	at ru.tinkoff.gatling.kafka.javaapi.protocol.KafkaProtocolBuilderPropertiesStep.properties(KafkaProtocolBuilderPropertiesStep.java:21)
```

The reason seems to be because "coverageEnabled := true" is in the build.sbt. The file would exist on the machine used to build, hence your local tests likely passed.

It looks like coverageEnabled should be set to false prior to building/packaging the plugin, to ensure the code is not instrumented by scoverage.

**Comment by barryperez-sky** [comment]
Set coverageEnabled to false locally, pushed to local Maven repo and was able to run - so confirmed that this will fix the issue if you could update this and publish a new version
